// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { ValueProto } from './value-proto.js';


export class ArrayItemValueProto {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):ArrayItemValueProto {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsArrayItemValueProto(bb:flatbuffers.ByteBuffer, obj?:ArrayItemValueProto):ArrayItemValueProto {
  return (obj || new ArrayItemValueProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsArrayItemValueProto(bb:flatbuffers.ByteBuffer, obj?:ArrayItemValueProto):ArrayItemValueProto {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ArrayItemValueProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

index():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

value(obj?:ValueProto):ValueProto|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new ValueProto()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startArrayItemValueProto(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addIndex(builder:flatbuffers.Builder, index:number) {
  builder.addFieldInt32(0, index, 0);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, valueOffset, 0);
}

static endArrayItemValueProto(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
