// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { MethodArgumentProto } from './method-argument-proto.js';


export class ConstructorProto {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):ConstructorProto {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsConstructorProto(bb:flatbuffers.ByteBuffer, obj?:ConstructorProto):ConstructorProto {
  return (obj || new ConstructorProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsConstructorProto(bb:flatbuffers.ByteBuffer, obj?:ConstructorProto):ConstructorProto {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ConstructorProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

arguments(index: number, obj?:MethodArgumentProto):MethodArgumentProto|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new MethodArgumentProto()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

argumentsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startConstructorProto(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addArguments(builder:flatbuffers.Builder, argumentsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, argumentsOffset, 0);
}

static createArgumentsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startArgumentsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endConstructorProto(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createConstructorProto(builder:flatbuffers.Builder, argumentsOffset:flatbuffers.Offset):flatbuffers.Offset {
  ConstructorProto.startConstructorProto(builder);
  ConstructorProto.addArguments(builder, argumentsOffset);
  return ConstructorProto.endConstructorProto(builder);
}
}
