// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { ConstructorProto } from './constructor-proto.js';
import { MethodProto } from './method-proto.js';


export class DataClassProto {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):DataClassProto {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDataClassProto(bb:flatbuffers.ByteBuffer, obj?:DataClassProto):DataClassProto {
  return (obj || new DataClassProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDataClassProto(bb:flatbuffers.ByteBuffer, obj?:DataClassProto):DataClassProto {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DataClassProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

classId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

className():string|null
className(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
className(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

sourceCode():string|null
sourceCode(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
sourceCode(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

fileNameId():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

ctor(obj?:ConstructorProto):ConstructorProto|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new ConstructorProto()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

methods(index: number, obj?:MethodProto):MethodProto|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new MethodProto()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

methodsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startDataClassProto(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addClassId(builder:flatbuffers.Builder, classId:number) {
  builder.addFieldInt16(0, classId, 0);
}

static addClassName(builder:flatbuffers.Builder, classNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, classNameOffset, 0);
}

static addSourceCode(builder:flatbuffers.Builder, sourceCodeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, sourceCodeOffset, 0);
}

static addFileNameId(builder:flatbuffers.Builder, fileNameId:number) {
  builder.addFieldInt16(3, fileNameId, 0);
}

static addCtor(builder:flatbuffers.Builder, ctorOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, ctorOffset, 0);
}

static addMethods(builder:flatbuffers.Builder, methodsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, methodsOffset, 0);
}

static createMethodsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startMethodsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endDataClassProto(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 6) // class_name
  builder.requiredField(offset, 8) // source_code
  builder.requiredField(offset, 12) // ctor
  return offset;
}

}
