// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { DataDeltaBytesProto } from './data-delta-bytes-proto.js';


export class DataUpdateMessageProto {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):DataUpdateMessageProto {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDataUpdateMessageProto(bb:flatbuffers.ByteBuffer, obj?:DataUpdateMessageProto):DataUpdateMessageProto {
  return (obj || new DataUpdateMessageProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDataUpdateMessageProto(bb:flatbuffers.ByteBuffer, obj?:DataUpdateMessageProto):DataUpdateMessageProto {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DataUpdateMessageProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

deltas(index: number, obj?:DataDeltaBytesProto):DataDeltaBytesProto|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new DataDeltaBytesProto()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

deltasLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startDataUpdateMessageProto(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addDeltas(builder:flatbuffers.Builder, deltasOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, deltasOffset, 0);
}

static createDeltasVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startDeltasVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endDataUpdateMessageProto(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // deltas
  return offset;
}

static createDataUpdateMessageProto(builder:flatbuffers.Builder, deltasOffset:flatbuffers.Offset):flatbuffers.Offset {
  DataUpdateMessageProto.startDataUpdateMessageProto(builder);
  DataUpdateMessageProto.addDeltas(builder, deltasOffset);
  return DataUpdateMessageProto.endDataUpdateMessageProto(builder);
}
}
