// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class ErrorCodeResponseProto {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):ErrorCodeResponseProto {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsErrorCodeResponseProto(bb:flatbuffers.ByteBuffer, obj?:ErrorCodeResponseProto):ErrorCodeResponseProto {
  return (obj || new ErrorCodeResponseProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsErrorCodeResponseProto(bb:flatbuffers.ByteBuffer, obj?:ErrorCodeResponseProto):ErrorCodeResponseProto {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ErrorCodeResponseProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

errorCode():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

static startErrorCodeResponseProto(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addErrorCode(builder:flatbuffers.Builder, errorCode:number) {
  builder.addFieldInt16(0, errorCode, 0);
}

static endErrorCodeResponseProto(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createErrorCodeResponseProto(builder:flatbuffers.Builder, errorCode:number):flatbuffers.Offset {
  ErrorCodeResponseProto.startErrorCodeResponseProto(builder);
  ErrorCodeResponseProto.addErrorCode(builder, errorCode);
  return ErrorCodeResponseProto.endErrorCodeResponseProto(builder);
}
}
