// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class SubscribeDataUpdatesResponseProto {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):SubscribeDataUpdatesResponseProto {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSubscribeDataUpdatesResponseProto(bb:flatbuffers.ByteBuffer, obj?:SubscribeDataUpdatesResponseProto):SubscribeDataUpdatesResponseProto {
  return (obj || new SubscribeDataUpdatesResponseProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSubscribeDataUpdatesResponseProto(bb:flatbuffers.ByteBuffer, obj?:SubscribeDataUpdatesResponseProto):SubscribeDataUpdatesResponseProto {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SubscribeDataUpdatesResponseProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startSubscribeDataUpdatesResponseProto(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endSubscribeDataUpdatesResponseProto(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSubscribeDataUpdatesResponseProto(builder:flatbuffers.Builder):flatbuffers.Offset {
  SubscribeDataUpdatesResponseProto.startSubscribeDataUpdatesResponseProto(builder);
  return SubscribeDataUpdatesResponseProto.endSubscribeDataUpdatesResponseProto(builder);
}
}
