// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class UndefinedValueProto {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):UndefinedValueProto {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUndefinedValueProto(bb:flatbuffers.ByteBuffer, obj?:UndefinedValueProto):UndefinedValueProto {
  return (obj || new UndefinedValueProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUndefinedValueProto(bb:flatbuffers.ByteBuffer, obj?:UndefinedValueProto):UndefinedValueProto {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UndefinedValueProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startUndefinedValueProto(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endUndefinedValueProto(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createUndefinedValueProto(builder:flatbuffers.Builder):flatbuffers.Offset {
  UndefinedValueProto.startUndefinedValueProto(builder);
  return UndefinedValueProto.endUndefinedValueProto(builder);
}
}
