// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class UnsubscribeDataUpdatesResponseProto {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):UnsubscribeDataUpdatesResponseProto {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUnsubscribeDataUpdatesResponseProto(bb:flatbuffers.ByteBuffer, obj?:UnsubscribeDataUpdatesResponseProto):UnsubscribeDataUpdatesResponseProto {
  return (obj || new UnsubscribeDataUpdatesResponseProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUnsubscribeDataUpdatesResponseProto(bb:flatbuffers.ByteBuffer, obj?:UnsubscribeDataUpdatesResponseProto):UnsubscribeDataUpdatesResponseProto {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UnsubscribeDataUpdatesResponseProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startUnsubscribeDataUpdatesResponseProto(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endUnsubscribeDataUpdatesResponseProto(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createUnsubscribeDataUpdatesResponseProto(builder:flatbuffers.Builder):flatbuffers.Offset {
  UnsubscribeDataUpdatesResponseProto.startUnsubscribeDataUpdatesResponseProto(builder);
  return UnsubscribeDataUpdatesResponseProto.endUnsubscribeDataUpdatesResponseProto(builder);
}
}
