// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class UnsubscribeMessageResponseProto {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):UnsubscribeMessageResponseProto {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUnsubscribeMessageResponseProto(bb:flatbuffers.ByteBuffer, obj?:UnsubscribeMessageResponseProto):UnsubscribeMessageResponseProto {
  return (obj || new UnsubscribeMessageResponseProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUnsubscribeMessageResponseProto(bb:flatbuffers.ByteBuffer, obj?:UnsubscribeMessageResponseProto):UnsubscribeMessageResponseProto {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UnsubscribeMessageResponseProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startUnsubscribeMessageResponseProto(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endUnsubscribeMessageResponseProto(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createUnsubscribeMessageResponseProto(builder:flatbuffers.Builder):flatbuffers.Offset {
  UnsubscribeMessageResponseProto.startUnsubscribeMessageResponseProto(builder);
  return UnsubscribeMessageResponseProto.endUnsubscribeMessageResponseProto(builder);
}
}
