// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { UserMessageUnionProto, unionToUserMessageUnionProto, unionListToUserMessageUnionProto } from './user-message-union-proto.js';


export class UserMessageUnionWrapperProto {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):UserMessageUnionWrapperProto {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUserMessageUnionWrapperProto(bb:flatbuffers.ByteBuffer, obj?:UserMessageUnionWrapperProto):UserMessageUnionWrapperProto {
  return (obj || new UserMessageUnionWrapperProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUserMessageUnionWrapperProto(bb:flatbuffers.ByteBuffer, obj?:UserMessageUnionWrapperProto):UserMessageUnionWrapperProto {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UserMessageUnionWrapperProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

valueType():UserMessageUnionProto {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : UserMessageUnionProto.NONE;
}

value<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startUserMessageUnionWrapperProto(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addValueType(builder:flatbuffers.Builder, valueType:UserMessageUnionProto) {
  builder.addFieldInt8(0, valueType, UserMessageUnionProto.NONE);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, valueOffset, 0);
}

static endUserMessageUnionWrapperProto(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createUserMessageUnionWrapperProto(builder:flatbuffers.Builder, valueType:UserMessageUnionProto, valueOffset:flatbuffers.Offset):flatbuffers.Offset {
  UserMessageUnionWrapperProto.startUserMessageUnionWrapperProto(builder);
  UserMessageUnionWrapperProto.addValueType(builder, valueType);
  UserMessageUnionWrapperProto.addValue(builder, valueOffset);
  return UserMessageUnionWrapperProto.endUserMessageUnionWrapperProto(builder);
}
}
