// automatically generated by the FlatBuffers compiler, do not modify

import { CallServiceMethodResponseProto } from './call-service-method-response-proto.js';
import { ErrorCodeResponseProto } from './error-code-response-proto.js';
import { ExceptionResponseProto } from './exception-response-proto.js';
import { GetDataResponseProto } from './get-data-response-proto.js';
import { SaveDataResponseProto } from './save-data-response-proto.js';
import { SubscribeDataUpdatesResponseProto } from './subscribe-data-updates-response-proto.js';
import { SubscribeMessageResponseProto } from './subscribe-message-response-proto.js';
import { UnsubscribeDataUpdatesResponseProto } from './unsubscribe-data-updates-response-proto.js';
import { UnsubscribeMessageResponseProto } from './unsubscribe-message-response-proto.js';


export enum UserResponseUnionProto{
  NONE = 0,
  ErrorCodeResponseProto = 1,
  ExceptionResponseProto = 2,
  CallServiceMethodResponseProto = 3,
  GetDataResponseProto = 4,
  SaveDataResponseProto = 5,
  SubscribeMessageResponseProto = 6,
  UnsubscribeMessageResponseProto = 7,
  SubscribeDataUpdatesResponseProto = 8,
  UnsubscribeDataUpdatesResponseProto = 9
}

export function unionToUserResponseUnionProto(
  type: UserResponseUnionProto,
  accessor: (obj:CallServiceMethodResponseProto|ErrorCodeResponseProto|ExceptionResponseProto|GetDataResponseProto|SaveDataResponseProto|SubscribeDataUpdatesResponseProto|SubscribeMessageResponseProto|UnsubscribeDataUpdatesResponseProto|UnsubscribeMessageResponseProto) => CallServiceMethodResponseProto|ErrorCodeResponseProto|ExceptionResponseProto|GetDataResponseProto|SaveDataResponseProto|SubscribeDataUpdatesResponseProto|SubscribeMessageResponseProto|UnsubscribeDataUpdatesResponseProto|UnsubscribeMessageResponseProto|null
): CallServiceMethodResponseProto|ErrorCodeResponseProto|ExceptionResponseProto|GetDataResponseProto|SaveDataResponseProto|SubscribeDataUpdatesResponseProto|SubscribeMessageResponseProto|UnsubscribeDataUpdatesResponseProto|UnsubscribeMessageResponseProto|null {
  switch(UserResponseUnionProto[type]) {
    case 'NONE': return null; 
    case 'ErrorCodeResponseProto': return accessor(new ErrorCodeResponseProto())! as ErrorCodeResponseProto;
    case 'ExceptionResponseProto': return accessor(new ExceptionResponseProto())! as ExceptionResponseProto;
    case 'CallServiceMethodResponseProto': return accessor(new CallServiceMethodResponseProto())! as CallServiceMethodResponseProto;
    case 'GetDataResponseProto': return accessor(new GetDataResponseProto())! as GetDataResponseProto;
    case 'SaveDataResponseProto': return accessor(new SaveDataResponseProto())! as SaveDataResponseProto;
    case 'SubscribeMessageResponseProto': return accessor(new SubscribeMessageResponseProto())! as SubscribeMessageResponseProto;
    case 'UnsubscribeMessageResponseProto': return accessor(new UnsubscribeMessageResponseProto())! as UnsubscribeMessageResponseProto;
    case 'SubscribeDataUpdatesResponseProto': return accessor(new SubscribeDataUpdatesResponseProto())! as SubscribeDataUpdatesResponseProto;
    case 'UnsubscribeDataUpdatesResponseProto': return accessor(new UnsubscribeDataUpdatesResponseProto())! as UnsubscribeDataUpdatesResponseProto;
    default: return null;
  }
}

export function unionListToUserResponseUnionProto(
  type: UserResponseUnionProto, 
  accessor: (index: number, obj:CallServiceMethodResponseProto|ErrorCodeResponseProto|ExceptionResponseProto|GetDataResponseProto|SaveDataResponseProto|SubscribeDataUpdatesResponseProto|SubscribeMessageResponseProto|UnsubscribeDataUpdatesResponseProto|UnsubscribeMessageResponseProto) => CallServiceMethodResponseProto|ErrorCodeResponseProto|ExceptionResponseProto|GetDataResponseProto|SaveDataResponseProto|SubscribeDataUpdatesResponseProto|SubscribeMessageResponseProto|UnsubscribeDataUpdatesResponseProto|UnsubscribeMessageResponseProto|null, 
  index: number
): CallServiceMethodResponseProto|ErrorCodeResponseProto|ExceptionResponseProto|GetDataResponseProto|SaveDataResponseProto|SubscribeDataUpdatesResponseProto|SubscribeMessageResponseProto|UnsubscribeDataUpdatesResponseProto|UnsubscribeMessageResponseProto|null {
  switch(UserResponseUnionProto[type]) {
    case 'NONE': return null; 
    case 'ErrorCodeResponseProto': return accessor(index, new ErrorCodeResponseProto())! as ErrorCodeResponseProto;
    case 'ExceptionResponseProto': return accessor(index, new ExceptionResponseProto())! as ExceptionResponseProto;
    case 'CallServiceMethodResponseProto': return accessor(index, new CallServiceMethodResponseProto())! as CallServiceMethodResponseProto;
    case 'GetDataResponseProto': return accessor(index, new GetDataResponseProto())! as GetDataResponseProto;
    case 'SaveDataResponseProto': return accessor(index, new SaveDataResponseProto())! as SaveDataResponseProto;
    case 'SubscribeMessageResponseProto': return accessor(index, new SubscribeMessageResponseProto())! as SubscribeMessageResponseProto;
    case 'UnsubscribeMessageResponseProto': return accessor(index, new UnsubscribeMessageResponseProto())! as UnsubscribeMessageResponseProto;
    case 'SubscribeDataUpdatesResponseProto': return accessor(index, new SubscribeDataUpdatesResponseProto())! as SubscribeDataUpdatesResponseProto;
    case 'UnsubscribeDataUpdatesResponseProto': return accessor(index, new UnsubscribeDataUpdatesResponseProto())! as UnsubscribeDataUpdatesResponseProto;
    default: return null;
  }
}

