// automatically generated by the FlatBuffers compiler, do not modify

import { DataUpdateMessageProto } from './data-update-message-proto.js';
import { MessageMessageProto } from './message-message-proto.js';


export enum UserMessageUnionProto{
  NONE = 0,
  DataUpdateMessageProto = 1,
  MessageMessageProto = 2
}

export function unionToUserMessageUnionProto(
  type: UserMessageUnionProto,
  accessor: (obj:DataUpdateMessageProto|MessageMessageProto) => DataUpdateMessageProto|MessageMessageProto|null
): DataUpdateMessageProto|MessageMessageProto|null {
  switch(UserMessageUnionProto[type]) {
    case 'NONE': return null; 
    case 'DataUpdateMessageProto': return accessor(new DataUpdateMessageProto())! as DataUpdateMessageProto;
    case 'MessageMessageProto': return accessor(new MessageMessageProto())! as MessageMessageProto;
    default: return null;
  }
}

export function unionListToUserMessageUnionProto(
  type: UserMessageUnionProto, 
  accessor: (index: number, obj:DataUpdateMessageProto|MessageMessageProto) => DataUpdateMessageProto|MessageMessageProto|null, 
  index: number
): DataUpdateMessageProto|MessageMessageProto|null {
  switch(UserMessageUnionProto[type]) {
    case 'NONE': return null; 
    case 'DataUpdateMessageProto': return accessor(index, new DataUpdateMessageProto())! as DataUpdateMessageProto;
    case 'MessageMessageProto': return accessor(index, new MessageMessageProto())! as MessageMessageProto;
    default: return null;
  }
}

