// automatically generated by the FlatBuffers compiler, do not modify

import { DataReferenceValueProto } from './data-reference-value-proto.js';
import { ServiceReferenceValueProto } from './service-reference-value-proto.js';


export enum WarpReferenceUnionProto{
  NONE = 0,
  DataReferenceValueProto = 1,
  ServiceReferenceValueProto = 2
}

export function unionToWarpReferenceUnionProto(
  type: WarpReferenceUnionProto,
  accessor: (obj:DataReferenceValueProto|ServiceReferenceValueProto) => DataReferenceValueProto|ServiceReferenceValueProto|null
): DataReferenceValueProto|ServiceReferenceValueProto|null {
  switch(WarpReferenceUnionProto[type]) {
    case 'NONE': return null; 
    case 'DataReferenceValueProto': return accessor(new DataReferenceValueProto())! as DataReferenceValueProto;
    case 'ServiceReferenceValueProto': return accessor(new ServiceReferenceValueProto())! as ServiceReferenceValueProto;
    default: return null;
  }
}

export function unionListToWarpReferenceUnionProto(
  type: WarpReferenceUnionProto, 
  accessor: (index: number, obj:DataReferenceValueProto|ServiceReferenceValueProto) => DataReferenceValueProto|ServiceReferenceValueProto|null, 
  index: number
): DataReferenceValueProto|ServiceReferenceValueProto|null {
  switch(WarpReferenceUnionProto[type]) {
    case 'NONE': return null; 
    case 'DataReferenceValueProto': return accessor(index, new DataReferenceValueProto())! as DataReferenceValueProto;
    case 'ServiceReferenceValueProto': return accessor(index, new ServiceReferenceValueProto())! as ServiceReferenceValueProto;
    default: return null;
  }
}

