// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class ConsoleLogMessageProto {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):ConsoleLogMessageProto {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsConsoleLogMessageProto(bb:flatbuffers.ByteBuffer, obj?:ConsoleLogMessageProto):ConsoleLogMessageProto {
  return (obj || new ConsoleLogMessageProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsConsoleLogMessageProto(bb:flatbuffers.ByteBuffer, obj?:ConsoleLogMessageProto):ConsoleLogMessageProto {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ConsoleLogMessageProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

message():string|null
message(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
message(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

error():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startConsoleLogMessageProto(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addMessage(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, messageOffset, 0);
}

static addError(builder:flatbuffers.Builder, error:boolean) {
  builder.addFieldInt8(1, +error, +false);
}

static endConsoleLogMessageProto(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // message
  return offset;
}

static createConsoleLogMessageProto(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset, error:boolean):flatbuffers.Offset {
  ConsoleLogMessageProto.startConsoleLogMessageProto(builder);
  ConsoleLogMessageProto.addMessage(builder, messageOffset);
  ConsoleLogMessageProto.addError(builder, error);
  return ConsoleLogMessageProto.endConsoleLogMessageProto(builder);
}
}
