// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { MethodArgumentProto } from './method-argument-proto.js';


export class FreeFunctionProto {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):FreeFunctionProto {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFreeFunctionProto(bb:flatbuffers.ByteBuffer, obj?:FreeFunctionProto):FreeFunctionProto {
  return (obj || new FreeFunctionProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFreeFunctionProto(bb:flatbuffers.ByteBuffer, obj?:FreeFunctionProto):FreeFunctionProto {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FreeFunctionProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sourceCode():string|null
sourceCode(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
sourceCode(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

functionName():string|null
functionName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
functionName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

arguments(index: number, obj?:MethodArgumentProto):MethodArgumentProto|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new MethodArgumentProto()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

argumentsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

returnType():string|null
returnType(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
returnType(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startFreeFunctionProto(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addSourceCode(builder:flatbuffers.Builder, sourceCodeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, sourceCodeOffset, 0);
}

static addFunctionName(builder:flatbuffers.Builder, functionNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, functionNameOffset, 0);
}

static addArguments(builder:flatbuffers.Builder, argumentsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, argumentsOffset, 0);
}

static createArgumentsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startArgumentsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addReturnType(builder:flatbuffers.Builder, returnTypeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, returnTypeOffset, 0);
}

static endFreeFunctionProto(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // source_code
  return offset;
}

static createFreeFunctionProto(builder:flatbuffers.Builder, sourceCodeOffset:flatbuffers.Offset, functionNameOffset:flatbuffers.Offset, argumentsOffset:flatbuffers.Offset, returnTypeOffset:flatbuffers.Offset):flatbuffers.Offset {
  FreeFunctionProto.startFreeFunctionProto(builder);
  FreeFunctionProto.addSourceCode(builder, sourceCodeOffset);
  FreeFunctionProto.addFunctionName(builder, functionNameOffset);
  FreeFunctionProto.addArguments(builder, argumentsOffset);
  FreeFunctionProto.addReturnType(builder, returnTypeOffset);
  return FreeFunctionProto.endFreeFunctionProto(builder);
}
}
