// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { MapValueItemProto } from './map-value-item-proto.js';


export class MapValueProto {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):MapValueProto {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMapValueProto(bb:flatbuffers.ByteBuffer, obj?:MapValueProto):MapValueProto {
  return (obj || new MapValueProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMapValueProto(bb:flatbuffers.ByteBuffer, obj?:MapValueProto):MapValueProto {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MapValueProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

items(index: number, obj?:MapValueItemProto):MapValueItemProto|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new MapValueItemProto()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

itemsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startMapValueProto(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addItems(builder:flatbuffers.Builder, itemsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, itemsOffset, 0);
}

static createItemsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startItemsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endMapValueProto(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createMapValueProto(builder:flatbuffers.Builder, itemsOffset:flatbuffers.Offset):flatbuffers.Offset {
  MapValueProto.startMapValueProto(builder);
  MapValueProto.addItems(builder, itemsOffset);
  return MapValueProto.endMapValueProto(builder);
}
}
