// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { ValueProto } from './value-proto.js';


export class MapValueItemProto {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):MapValueItemProto {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMapValueItemProto(bb:flatbuffers.ByteBuffer, obj?:MapValueItemProto):MapValueItemProto {
  return (obj || new MapValueItemProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMapValueItemProto(bb:flatbuffers.ByteBuffer, obj?:MapValueItemProto):MapValueItemProto {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MapValueItemProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

key(obj?:ValueProto):ValueProto|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new ValueProto()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

value(obj?:ValueProto):ValueProto|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new ValueProto()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startMapValueItemProto(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addKey(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, keyOffset, 0);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, valueOffset, 0);
}

static endMapValueItemProto(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
