// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { MethodArgumentProto } from './method-argument-proto.js';
import { MethodKindProto } from './method-kind-proto.js';


export class MethodProto {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):MethodProto {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMethodProto(bb:flatbuffers.ByteBuffer, obj?:MethodProto):MethodProto {
  return (obj || new MethodProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMethodProto(bb:flatbuffers.ByteBuffer, obj?:MethodProto):MethodProto {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MethodProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

methodName():string|null
methodName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
methodName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

methodKind():MethodKindProto {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : MethodKindProto.Normal;
}

arguments(index: number, obj?:MethodArgumentProto):MethodArgumentProto|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new MethodArgumentProto()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

argumentsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

returnType():string|null
returnType(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
returnType(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startMethodProto(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addMethodName(builder:flatbuffers.Builder, methodNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, methodNameOffset, 0);
}

static addMethodKind(builder:flatbuffers.Builder, methodKind:MethodKindProto) {
  builder.addFieldInt8(1, methodKind, MethodKindProto.Normal);
}

static addArguments(builder:flatbuffers.Builder, argumentsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, argumentsOffset, 0);
}

static createArgumentsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startArgumentsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addReturnType(builder:flatbuffers.Builder, returnTypeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, returnTypeOffset, 0);
}

static endMethodProto(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // method_name
  return offset;
}

static createMethodProto(builder:flatbuffers.Builder, methodNameOffset:flatbuffers.Offset, methodKind:MethodKindProto, argumentsOffset:flatbuffers.Offset, returnTypeOffset:flatbuffers.Offset):flatbuffers.Offset {
  MethodProto.startMethodProto(builder);
  MethodProto.addMethodName(builder, methodNameOffset);
  MethodProto.addMethodKind(builder, methodKind);
  MethodProto.addArguments(builder, argumentsOffset);
  MethodProto.addReturnType(builder, returnTypeOffset);
  return MethodProto.endMethodProto(builder);
}
}
