// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class NullValueProto {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):NullValueProto {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsNullValueProto(bb:flatbuffers.ByteBuffer, obj?:NullValueProto):NullValueProto {
  return (obj || new NullValueProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsNullValueProto(bb:flatbuffers.ByteBuffer, obj?:NullValueProto):NullValueProto {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new NullValueProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startNullValueProto(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endNullValueProto(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createNullValueProto(builder:flatbuffers.Builder):flatbuffers.Offset {
  NullValueProto.startNullValueProto(builder);
  return NullValueProto.endNullValueProto(builder);
}
}
