// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { DataHandleProto } from './data-handle-proto.js';


export class SaveDataResponseProto {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):SaveDataResponseProto {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSaveDataResponseProto(bb:flatbuffers.ByteBuffer, obj?:SaveDataResponseProto):SaveDataResponseProto {
  return (obj || new SaveDataResponseProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSaveDataResponseProto(bb:flatbuffers.ByteBuffer, obj?:SaveDataResponseProto):SaveDataResponseProto {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SaveDataResponseProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

handles(index: number, obj?:DataHandleProto):DataHandleProto|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new DataHandleProto()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

handlesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startSaveDataResponseProto(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addHandles(builder:flatbuffers.Builder, handlesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, handlesOffset, 0);
}

static createHandlesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startHandlesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endSaveDataResponseProto(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // handles
  return offset;
}

static createSaveDataResponseProto(builder:flatbuffers.Builder, handlesOffset:flatbuffers.Offset):flatbuffers.Offset {
  SaveDataResponseProto.startSaveDataResponseProto(builder);
  SaveDataResponseProto.addHandles(builder, handlesOffset);
  return SaveDataResponseProto.endSaveDataResponseProto(builder);
}
}
