// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class SubscribeMessageResponseProto {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):SubscribeMessageResponseProto {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSubscribeMessageResponseProto(bb:flatbuffers.ByteBuffer, obj?:SubscribeMessageResponseProto):SubscribeMessageResponseProto {
  return (obj || new SubscribeMessageResponseProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSubscribeMessageResponseProto(bb:flatbuffers.ByteBuffer, obj?:SubscribeMessageResponseProto):SubscribeMessageResponseProto {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SubscribeMessageResponseProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startSubscribeMessageResponseProto(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endSubscribeMessageResponseProto(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSubscribeMessageResponseProto(builder:flatbuffers.Builder):flatbuffers.Offset {
  SubscribeMessageResponseProto.startSubscribeMessageResponseProto(builder);
  return SubscribeMessageResponseProto.endSubscribeMessageResponseProto(builder);
}
}
