// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { UserResponseUnionProto, unionToUserResponseUnionProto, unionListToUserResponseUnionProto } from './user-response-union-proto.js';


export class UserResponseUnionWrapperProto {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):UserResponseUnionWrapperProto {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUserResponseUnionWrapperProto(bb:flatbuffers.ByteBuffer, obj?:UserResponseUnionWrapperProto):UserResponseUnionWrapperProto {
  return (obj || new UserResponseUnionWrapperProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUserResponseUnionWrapperProto(bb:flatbuffers.ByteBuffer, obj?:UserResponseUnionWrapperProto):UserResponseUnionWrapperProto {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UserResponseUnionWrapperProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

valueType():UserResponseUnionProto {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : UserResponseUnionProto.NONE;
}

value<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startUserResponseUnionWrapperProto(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addValueType(builder:flatbuffers.Builder, valueType:UserResponseUnionProto) {
  builder.addFieldInt8(0, valueType, UserResponseUnionProto.NONE);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, valueOffset, 0);
}

static endUserResponseUnionWrapperProto(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createUserResponseUnionWrapperProto(builder:flatbuffers.Builder, valueType:UserResponseUnionProto, valueOffset:flatbuffers.Offset):flatbuffers.Offset {
  UserResponseUnionWrapperProto.startUserResponseUnionWrapperProto(builder);
  UserResponseUnionWrapperProto.addValueType(builder, valueType);
  UserResponseUnionWrapperProto.addValue(builder, valueOffset);
  return UserResponseUnionWrapperProto.endUserResponseUnionWrapperProto(builder);
}
}
