// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { ValueUnionProto, unionToValueUnionProto, unionListToValueUnionProto } from './value-union-proto.js';


export class ValueProto {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):ValueProto {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsValueProto(bb:flatbuffers.ByteBuffer, obj?:ValueProto):ValueProto {
  return (obj || new ValueProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsValueProto(bb:flatbuffers.ByteBuffer, obj?:ValueProto):ValueProto {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ValueProto()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

valueType():ValueUnionProto {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ValueUnionProto.NONE;
}

value<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startValueProto(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addValueType(builder:flatbuffers.Builder, valueType:ValueUnionProto) {
  builder.addFieldInt8(0, valueType, ValueUnionProto.NONE);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, valueOffset, 0);
}

static endValueProto(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createValueProto(builder:flatbuffers.Builder, valueType:ValueUnionProto, valueOffset:flatbuffers.Offset):flatbuffers.Offset {
  ValueProto.startValueProto(builder);
  ValueProto.addValueType(builder, valueType);
  ValueProto.addValue(builder, valueOffset);
  return ValueProto.endValueProto(builder);
}
}
